### ISSUE TITLE
bug: document can not be generated

### ISSUE THREAD

**Issue by idanran** [denoland/apiland#78] opened 2022-11-19 13:34 UTC
https://deno.land/x/dnlibob@0.11.1/mod.ts
It prompt: The documentation for this module is currently unavailable.
I guess it might be caused by `@deno-types`

deps.ts:
```ts
export { Logger } from 'https://deno.land/x/reggol_deno@1.3.1/mod.ts'
// @deno-types="https://deno.land/x/msgpackr@v1.8.0/index.d.ts"
export { pack, unpack } from 'https://deno.land/x/msgpackr@v1.8.0/index.js'
export { serve } from 'https://deno.land/std@0.165.0/http/server.ts'
```

**Comment by crowlKats** [comment] 2023-01-08 07:30
so there are 2 issues:
for version 0.11.1 of the module, the following error occurs:
```
Error: stream
    at __wbg_new_651776e932b7e9c7 (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc.generated.js:332:19)
    at <anonymous> (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc_bg.wasm:1:2028533)
    at <anonymous> (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc_bg.wasm:1:513898)
    at <anonymous> (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc_bg.wasm:1:1521674)
    at <anonymous> (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc_bg.wasm:1:1515742)
    at <anonymous> (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc_bg.wasm:1:1978976)
    at __wbg_adapter_16 (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc.generated.js:205:6)
    at real (https://deno.land/x/deno_doc@0.50.0/lib/deno_doc.generated.js:189:14)
Error generating doc nodes for "dnlibob@0.11.1/deps.ts":
```

for version 0.16.1, the problem is usage of npm specifiers

**Comment by crowlKats** [comment] 2023-01-08 18:38
ok so the first problem is due to that @deno-types importing `"stream"`.

**Comment by crowlKats** [comment] 2023-06-01 02:43
Closing at its working now.

**Closed by crowlKats** 2023-06-01 02:43 UTC
